#!/usr/bin/env bash
# tests/test-roost-config-migration.sh — `roost init` carries a legacy
# ~/.config/amux/amux.conf across to ~/.config/roost/roost.conf, translating
# @amux-* keys to @roost-* and leaving @agent_* keys (and the old file
# itself) untouched. The running amux server may still be reading the old
# file, so this never writes, moves, or deletes it.
#
# Cases 6-10 cover the one thing migration does beyond the key rename:
# backfilling @roost-glyph-error for a legacy config written before the
# `error` state existed. Those cases assert the VALUE of every glyph line, not
# just that a key is present — the process lesson in docs/known-gaps.md is
# that the init test once asserted an option NAME only, and a bug that shifted
# every glyph by one position passed throughout.
set -u
. "$(dirname "$0")/lib.sh"
HERE="$(cd "$(dirname "$0")/.." && pwd)"
ROOST_INIT="$HERE/scripts/roost-init"

# --- Case 1: XDG_CONFIG_HOME set, legacy present, new file absent. ---------
cfgdir="$(mktemp -d /tmp/amx.XXXX)"
homedir="$(mktemp -d /tmp/amx.XXXX)"   # decoy HOME: must never be touched
mkdir -p "$cfgdir/amux"
legacy="$cfgdir/amux/amux.conf"
cat > "$legacy" <<'EOF'
# Generated by amux init. Re-run amux init to change, or edit by hand.
set -g @amux-notify-backend "auto"
set -g @amux-color-active-bg "#ff0000"
set -g @agent_state "idle"
set -g @agent_glyph "🟢"
EOF
chmod 640 "$legacy"   # deterministic, umask-independent: migration should carry this exact mode

before_sum="$(cksum "$legacy")"
before_bytes="$(wc -c < "$legacy")"

# The tty guard runs before migration (a scripted, non-interactive caller
# must clear it the same way any other roost-init invocation does), so pipe
# empty scripted stdin and set ROOST_INIT_ANSWERS=- like any other
# non-interactive caller — migration itself still asks no questions.
out="$(printf '' | HOME="$homedir" XDG_CONFIG_HOME="$cfgdir" ROOST_INIT_ANSWERS=- "$ROOST_INIT" 2>&1)"
rc=$?

newconf="$cfgdir/roost/roost.conf"

assert_eq "$rc" "0" "migration exits 0"
[ -f "$newconf" ] && assert_eq ok ok "writes new roost.conf" || assert_eq "" exists "writes new roost.conf"

assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @roost-notify-backend "auto"' "translates @amux-notify-backend, value carried across"
assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @roost-color-active-bg "#ff0000"' "translates @amux-color-active-bg, value carried across"
assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @agent_state "idle"' "leaves unbranded @agent_state key unchanged"
assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @agent_glyph "🟢"' "leaves unbranded @agent_glyph key unchanged"

case "$(cat "$newconf" 2>/dev/null)" in
  *@amux-*) assert_eq "has-amux-keys" "no-amux-keys" "new file has no leftover @amux- keys" ;;
  *)        assert_eq ok ok "new file has no leftover @amux- keys" ;;
esac

# The header comment is translated too, not just @amux-* keys — a migrated
# file should not tell the user to re-run the command that no longer exists.
assert_contains "$(cat "$newconf" 2>/dev/null)" "roost init" "migrated header mentions roost init, not the old command"
case "$(cat "$newconf" 2>/dev/null)" in
  *"amux init"*) assert_eq "mentions-amux-init" "no-amux-init" "migrated header no longer tells the user to re-run amux init" ;;
  *)             assert_eq ok ok "migrated header no longer tells the user to re-run amux init" ;;
esac

# File permissions carry across from the legacy file, not umask defaults.
# GNU-first, same ordering as scripts/lib/roost-config.sh: GNU `stat -f`
# means "filesystem status" and would not fail, so the fallback must be tried
# second or it never fires on Linux.
newmode="$(stat -c '%a' "$newconf" 2>/dev/null || stat -f '%Lp' "$newconf" 2>/dev/null)"
assert_eq "$newmode" "640" "migrated roost.conf keeps the legacy file's permissions (640)"

after_sum="$(cksum "$legacy")"
after_bytes="$(wc -c < "$legacy")"
assert_eq "$after_sum" "$before_sum" "legacy amux.conf is byte-identical after migration (cksum)"
assert_eq "$after_bytes" "$before_bytes" "legacy amux.conf size unchanged after migration"

if [ -e "$homedir/.config" ]; then
  assert_eq "touched" "untouched" "decoy HOME is never written to when XDG_CONFIG_HOME is set"
else
  assert_eq ok ok "decoy HOME is never written to when XDG_CONFIG_HOME is set"
fi

rm -rf "$cfgdir" "$homedir"

# --- Case 2: no XDG_CONFIG_HOME, falls back to $HOME/.config. --------------
homedir2="$(mktemp -d /tmp/amx.XXXX)"
mkdir -p "$homedir2/.config/amux"
legacy2="$homedir2/.config/amux/amux.conf"
printf 'set -g @amux-glyph-idle "zzz"\n' > "$legacy2"
before2="$(cksum "$legacy2")"

printf '' | env -u XDG_CONFIG_HOME HOME="$homedir2" ROOST_INIT_ANSWERS=- "$ROOST_INIT" >/dev/null 2>&1
newconf2="$homedir2/.config/roost/roost.conf"
[ -f "$newconf2" ] && assert_eq ok ok "HOME-only fallback: writes new roost.conf" || assert_eq "" exists "HOME-only fallback: writes new roost.conf"
assert_contains "$(cat "$newconf2" 2>/dev/null)" 'set -g @roost-glyph-idle "zzz"' "HOME-only fallback: translates key and value"
after2="$(cksum "$legacy2")"
assert_eq "$after2" "$before2" "HOME-only fallback: legacy amux.conf untouched"

rm -rf "$homedir2"

# --- Case 3: roost.conf already exists -> migration must not run at all. ---
# The tty guard now runs first, so to even reach the migration `if` we must
# clear it with ROOST_INIT_ANSWERS=- and piped stdin — same as Cases 1/2.
# But here the target ALREADY exists, so the migration condition
# (`[ ! -f "$target" ]`) is false and the script instead falls through into
# the normal interactive flow, which legitimately backs up and rewrites an
# existing roost.conf from the (empty/default) answers. That rewrite is
# real, correct `roost init` behaviour and is not what this case is testing;
# a plain "is the file byte-identical" assertion would be vacuously true for
# the wrong reason before the guard moved, and would flip to a false
# failure now that clearing the guard is required to reach the code at all.
# So this case asserts the two things that actually distinguish "migration
# ran instead" from "the normal ask-flow ran": (a) the normal flow always
# backs up an existing target before overwriting — migration's code path
# has no backup step at all, so a missing backup means migration clobbered
# it directly; (b) migration's output would be byte-identical to a raw,
# unbackuped sed translation of the legacy file — the interactive flow's
# output never is, because it always carries the full default key set.
# Verified against a mutant (`if [ -f "$legacy" ]`, dropping the
# target-absent check) that both assertions catch: no .bak was written and
# the resulting file WAS the raw translation.
cfgdir3="$(mktemp -d /tmp/amx.XXXX)"
mkdir -p "$cfgdir3/amux" "$cfgdir3/roost"
legacy3="$cfgdir3/amux/amux.conf"
printf 'set -g @amux-notify-backend "auto"\n' > "$legacy3"
printf '# already migrated / hand-written\nset -g @roost-notify-backend "tmux"\n' > "$cfgdir3/roost/roost.conf"
legacy3_before="$(cksum "$legacy3")"
naive_translation="$(sed 's/@amux-/@roost-/g' "$legacy3")"

printf '' | HOME=/nonexistent XDG_CONFIG_HOME="$cfgdir3" ROOST_INIT_ANSWERS=- "$ROOST_INIT" >/dev/null 2>&1

if ls "$cfgdir3/roost/"*.bak >/dev/null 2>&1; then
  assert_eq ok ok "an existing roost.conf is backed up before any rewrite (proves the normal flow ran, not migration)"
else
  assert_eq "" backup "an existing roost.conf is backed up before any rewrite (proves the normal flow ran, not migration)"
fi

actual="$(cat "$cfgdir3/roost/roost.conf" 2>/dev/null)"
if [ "$actual" = "$naive_translation" ]; then
  assert_eq "raw-migration-output" "interactive-output" "existing roost.conf's new content is not migration's raw translation of the legacy file"
else
  assert_eq ok ok "existing roost.conf's new content is not migration's raw translation of the legacy file"
fi

legacy3_after="$(cksum "$legacy3")"
assert_eq "$legacy3_after" "$legacy3_before" "legacy amux.conf untouched even when roost.conf already exists"

rm -rf "$cfgdir3"

# --- Case 4: the tty guard precedes migration -> a non-tty call with no ----
# --- scripted answers must exit non-zero and write NOTHING, even though ----
# --- migration's own preconditions (legacy present, new file absent) hold. -
cfgdir4="$(mktemp -d /tmp/amx.XXXX)"
mkdir -p "$cfgdir4/amux"
printf 'set -g @amux-notify-backend "auto"\n' > "$cfgdir4/amux/amux.conf"

HOME=/nonexistent XDG_CONFIG_HOME="$cfgdir4" "$ROOST_INIT" </dev/null >/dev/null 2>&1
rc4=$?

assert_eq "$rc4" "1" "non-tty call with no scripted answers exits non-zero (guard, not migration, runs first)"
if [ -e "$cfgdir4/roost" ]; then
  assert_eq "wrote" "no-write" "a failing non-tty call writes no roost.conf, even though legacy exists and the new file is absent"
else
  assert_eq ok ok "a failing non-tty call writes no roost.conf, even though legacy exists and the new file is absent"
fi

rm -rf "$cfgdir4"

# --- Case 5: an unreadable legacy file fails loudly and leaves nothing -----
# --- behind, instead of silently writing a truncated/empty roost.conf. -----
# Migration used to `sed ... > "$target"` directly: the redirect truncates
# the target before sed ever runs, and sed's exit status was never checked.
# An unreadable (or otherwise failing-to-read) legacy file produced a
# zero-byte roost.conf, printed a success message, and exited 0 — and
# because migration only fires while roost.conf is absent, the loss was
# permanent; a later run would see the (empty) target and never retry.
# Root can read a chmod 000 file, so this case is a no-op under root rather
# than a false failure.
if [ "$(id -u)" = "0" ]; then
  printf '  SKIP: unreadable legacy file case (running as root, chmod 000 has no effect)\n'
else
  cfgdir5="$(mktemp -d /tmp/amx.XXXX)"
  mkdir -p "$cfgdir5/amux"
  legacy5="$cfgdir5/amux/amux.conf"
  printf 'set -g @amux-notify-backend "auto"\n' > "$legacy5"
  chmod 000 "$legacy5"

  printf '' | HOME=/nonexistent XDG_CONFIG_HOME="$cfgdir5" ROOST_INIT_ANSWERS=- "$ROOST_INIT" >/dev/null 2>/dev/null
  rc5=$?

  assert_eq "$rc5" "1" "an unreadable legacy file makes migration exit non-zero, not silently succeed"
  if [ -e "$cfgdir5/roost/roost.conf" ]; then
    assert_eq "wrote" "no-write" "an unreadable legacy file leaves no roost.conf behind (no truncated/empty file)"
  else
    assert_eq ok ok "an unreadable legacy file leaves no roost.conf behind (no truncated/empty file)"
  fi

  # Leftover .roost.XXXXXX temp files would also indicate a non-atomic write.
  if ls "$cfgdir5/roost"/.roost.* >/dev/null 2>&1; then
    assert_eq "leftover-tmp" "no-tmp" "no leftover migration temp file after a failed migration"
  else
    assert_eq ok ok "no leftover migration temp file after a failed migration"
  fi

  chmod 600 "$legacy5"   # restore before cleanup, in case rm needs to read the dir on some platform
  rm -rf "$cfgdir5"
fi

# --- Cases 6-10: the error-glyph backfill. ---------------------------------
# A user who picked ascii or nerd before the `error` state existed has four
# glyph lines and no @roost-glyph-error, so the bar falls back to
# tmux/roost.conf's global 💥 — an emoji in a bar they chose not to have emoji
# in, or a 2-cell glyph among 1-cell ones. A pure key rename would hand them a
# roost.conf that still predates the error state, so migration appends the
# fifth glyph its own four imply.
#
# Every assertion below is on a VALUE, and on the whole `set -g KEY "VALUE"`
# line, so a backfill that wrote the right key with the wrong glyph (or that
# shifted the set by one position, the exact bug docs/known-gaps.md records)
# fails here instead of passing on a name match.
#
# migrate_legacy DIRNAME <<'EOF' ... EOF -> seeds a legacy amux.conf from
# stdin, runs roost init, and echoes the path of the migrated roost.conf.
# HOME is a throwaway temp dir and XDG_CONFIG_HOME points inside it, so no
# case here can read or write the real ~/.config.
migrate_legacy() {
  local d="$1"
  mkdir -p "$d/amux"
  cat > "$d/amux/amux.conf"
  printf '' | HOME=/nonexistent XDG_CONFIG_HOME="$d" ROOST_INIT_ANSWERS=- "$ROOST_INIT" >/dev/null 2>&1
  printf '%s' "$d/roost/roost.conf"
}

# Case 6: a legacy ascii set gains the ascii error glyph, and only that line.
g6="$(mktemp -d /tmp/amx.XXXX)"
conf6="$(migrate_legacy "$g6" <<'EOF'
# Generated by amux init. Re-run amux init to change, or edit by hand.
set -g @amux-glyph-blocked "[!]"
set -g @amux-glyph-working "[~]"
set -g @amux-glyph-done    "[+]"
set -g @amux-glyph-idle    "[·]"
EOF
)"
body6="$(cat "$conf6" 2>/dev/null)"
assert_contains "$body6" 'set -g @roost-glyph-error   "[x]"' "ascii legacy set: backfills the ascii error glyph [x], not the emoji default"
assert_contains "$body6" 'set -g @roost-glyph-blocked "[!]"' "ascii legacy set: blocked glyph value survives the backfill"
assert_contains "$body6" 'set -g @roost-glyph-working "[~]"' "ascii legacy set: working glyph value survives the backfill"
assert_contains "$body6" 'set -g @roost-glyph-done    "[+]"' "ascii legacy set: done glyph value survives the backfill"
assert_contains "$body6" 'set -g @roost-glyph-idle    "[·]"' "ascii legacy set: idle glyph value survives the backfill"
# Exactly one error line: an append that ran twice, or one that also rewrote
# an existing line, would show up here and nowhere else.
assert_eq "$(grep -c '^set -g @roost-glyph-error ' "$conf6" 2>/dev/null | tr -d ' ')" "1" "ascii legacy set: exactly one @roost-glyph-error line is written"
rm -rf "$g6"

# Case 7: the nerd set's error glyph is written as real UTF-8 bytes. bash 3.2
# printf has no \u, so a regression that emitted an escape would silently put
# a literal backslash-u in the user's bar. Compare against the same bytes
# roost_glyphset produces, spelled out here rather than sourced, so the test
# does not agree with a broken table by construction.
g7="$(mktemp -d /tmp/amx.XXXX)"
nerd_blocked="$(printf '\xef\x81\xb1')"; nerd_working="$(printf '\xef\x89\x92')"
nerd_done="$(printf '\xef\x80\x8c')";    nerd_idle="$(printf '\xef\x86\x86')"
nerd_error="$(printf '\xef\x83\xa7')"
mkdir -p "$g7/amux"
{
  printf 'set -g @amux-glyph-blocked "%s"\n' "$nerd_blocked"
  printf 'set -g @amux-glyph-working "%s"\n' "$nerd_working"
  printf 'set -g @amux-glyph-done    "%s"\n' "$nerd_done"
  printf 'set -g @amux-glyph-idle    "%s"\n' "$nerd_idle"
} > "$g7/amux/amux.conf"
printf '' | HOME=/nonexistent XDG_CONFIG_HOME="$g7" ROOST_INIT_ANSWERS=- "$ROOST_INIT" >/dev/null 2>&1
assert_contains "$(cat "$g7/roost/roost.conf" 2>/dev/null)" "$(printf 'set -g @roost-glyph-error   "%s"' "$nerd_error")" "nerd legacy set: backfills the nerd error glyph as real UTF-8 bytes"
rm -rf "$g7"

# Case 8: four hand-customised glyphs match no named set, so there is nothing
# to derive a fifth from. Migration must leave the file alone rather than
# invent one — this is the case the backfill exists to NOT act on.
g8="$(mktemp -d /tmp/amx.XXXX)"
conf8="$(migrate_legacy "$g8" <<'EOF'
set -g @amux-glyph-blocked "!!"
set -g @amux-glyph-working "~~"
set -g @amux-glyph-done    "++"
set -g @amux-glyph-idle    ".."
EOF
)"
body8="$(cat "$conf8" 2>/dev/null)"
case "$body8" in
  *"@roost-glyph-error"*) assert_eq "backfilled" "left-alone" "a custom four-glyph set gets no invented error glyph" ;;
  *)                      assert_eq ok ok "a custom four-glyph set gets no invented error glyph" ;;
esac
assert_contains "$body8" 'set -g @roost-glyph-blocked "!!"' "a custom four-glyph set keeps its own blocked glyph"
assert_contains "$body8" 'set -g @roost-glyph-idle    ".."' "a custom four-glyph set keeps its own idle glyph"
rm -rf "$g8"

# Case 9: a legacy config that ALREADY carries an error glyph keeps the user's
# value. The backfill decides on the presence of the line, not on its value,
# so a deliberate custom error glyph on an otherwise-standard set survives.
g9="$(mktemp -d /tmp/amx.XXXX)"
conf9="$(migrate_legacy "$g9" <<'EOF'
set -g @amux-glyph-error   "(X)"
set -g @amux-glyph-blocked "[!]"
set -g @amux-glyph-working "[~]"
set -g @amux-glyph-done    "[+]"
set -g @amux-glyph-idle    "[·]"
EOF
)"
assert_contains "$(cat "$conf9" 2>/dev/null)" 'set -g @roost-glyph-error   "(X)"' "an existing custom error glyph is carried across, not overwritten with the set default"
assert_eq "$(grep -c '^set -g @roost-glyph-error ' "$conf9" 2>/dev/null | tr -d ' ')" "1" "an existing custom error glyph is not joined by a second, backfilled line"
rm -rf "$g9"

# Case 10: a legacy config with no glyph lines at all. Every glyph reads
# empty, which matches no set, so nothing is appended — the four missing
# glyphs are not evidence of a fifth.
g10="$(mktemp -d /tmp/amx.XXXX)"
conf10="$(migrate_legacy "$g10" <<'EOF'
set -g @amux-notify-backend "auto"
EOF
)"
case "$(cat "$conf10" 2>/dev/null)" in
  *"@roost-glyph"*) assert_eq "wrote-glyphs" "no-glyphs" "a legacy config with no glyph lines gains none" ;;
  *)                assert_eq ok ok "a legacy config with no glyph lines gains none" ;;
esac
assert_contains "$(cat "$conf10" 2>/dev/null)" 'set -g @roost-notify-backend "auto"' "a legacy config with no glyph lines still migrates its other keys"
rm -rf "$g10"
