#!/usr/bin/env bash
# tests/test-roost-config-migration.sh — `roost init` carries a legacy
# ~/.config/amux/amux.conf across to ~/.config/roost/roost.conf, translating
# @amux-* keys to @roost-* and leaving @agent_* keys (and the old file
# itself) untouched. The running amux server may still be reading the old
# file, so this never writes, moves, or deletes it.
set -u
. "$(dirname "$0")/lib.sh"
HERE="$(cd "$(dirname "$0")/.." && pwd)"
ROOST_INIT="$HERE/scripts/roost-init"

# --- Case 1: XDG_CONFIG_HOME set, legacy present, new file absent. ---------
cfgdir="$(mktemp -d /tmp/amx.XXXX)"
homedir="$(mktemp -d /tmp/amx.XXXX)"   # decoy HOME: must never be touched
mkdir -p "$cfgdir/amux"
legacy="$cfgdir/amux/amux.conf"
cat > "$legacy" <<'EOF'
# Generated by amux init. Re-run amux init to change, or edit by hand.
set -g @amux-notify-backend "auto"
set -g @amux-color-active-bg "#ff0000"
set -g @agent_state "idle"
set -g @agent_glyph "🟢"
EOF
chmod 640 "$legacy"   # deterministic, umask-independent: migration should carry this exact mode

before_sum="$(cksum "$legacy")"
before_bytes="$(wc -c < "$legacy")"

# The tty guard runs before migration (a scripted, non-interactive caller
# must clear it the same way any other roost-init invocation does), so pipe
# empty scripted stdin and set ROOST_INIT_ANSWERS=- like any other
# non-interactive caller — migration itself still asks no questions.
out="$(printf '' | HOME="$homedir" XDG_CONFIG_HOME="$cfgdir" ROOST_INIT_ANSWERS=- "$ROOST_INIT" 2>&1)"
rc=$?

newconf="$cfgdir/roost/roost.conf"

assert_eq "$rc" "0" "migration exits 0"
[ -f "$newconf" ] && assert_eq ok ok "writes new roost.conf" || assert_eq "" exists "writes new roost.conf"

assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @roost-notify-backend "auto"' "translates @amux-notify-backend, value carried across"
assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @roost-color-active-bg "#ff0000"' "translates @amux-color-active-bg, value carried across"
assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @agent_state "idle"' "leaves unbranded @agent_state key unchanged"
assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @agent_glyph "🟢"' "leaves unbranded @agent_glyph key unchanged"

case "$(cat "$newconf" 2>/dev/null)" in
  *@amux-*) assert_eq "has-amux-keys" "no-amux-keys" "new file has no leftover @amux- keys" ;;
  *)        assert_eq ok ok "new file has no leftover @amux- keys" ;;
esac

# The header comment is translated too, not just @amux-* keys — a migrated
# file should not tell the user to re-run the command that no longer exists.
assert_contains "$(cat "$newconf" 2>/dev/null)" "roost init" "migrated header mentions roost init, not the old command"
case "$(cat "$newconf" 2>/dev/null)" in
  *"amux init"*) assert_eq "mentions-amux-init" "no-amux-init" "migrated header no longer tells the user to re-run amux init" ;;
  *)             assert_eq ok ok "migrated header no longer tells the user to re-run amux init" ;;
esac

# File permissions carry across from the legacy file, not umask defaults.
# GNU-first, same ordering as scripts/lib/roost-config.sh: GNU `stat -f`
# means "filesystem status" and would not fail, so the fallback must be tried
# second or it never fires on Linux.
newmode="$(stat -c '%a' "$newconf" 2>/dev/null || stat -f '%Lp' "$newconf" 2>/dev/null)"
assert_eq "$newmode" "640" "migrated roost.conf keeps the legacy file's permissions (640)"

after_sum="$(cksum "$legacy")"
after_bytes="$(wc -c < "$legacy")"
assert_eq "$after_sum" "$before_sum" "legacy amux.conf is byte-identical after migration (cksum)"
assert_eq "$after_bytes" "$before_bytes" "legacy amux.conf size unchanged after migration"

if [ -e "$homedir/.config" ]; then
  assert_eq "touched" "untouched" "decoy HOME is never written to when XDG_CONFIG_HOME is set"
else
  assert_eq ok ok "decoy HOME is never written to when XDG_CONFIG_HOME is set"
fi

rm -rf "$cfgdir" "$homedir"

# --- Case 2: no XDG_CONFIG_HOME, falls back to $HOME/.config. --------------
homedir2="$(mktemp -d /tmp/amx.XXXX)"
mkdir -p "$homedir2/.config/amux"
legacy2="$homedir2/.config/amux/amux.conf"
printf 'set -g @amux-glyph-idle "zzz"\n' > "$legacy2"
before2="$(cksum "$legacy2")"

printf '' | env -u XDG_CONFIG_HOME HOME="$homedir2" ROOST_INIT_ANSWERS=- "$ROOST_INIT" >/dev/null 2>&1
newconf2="$homedir2/.config/roost/roost.conf"
[ -f "$newconf2" ] && assert_eq ok ok "HOME-only fallback: writes new roost.conf" || assert_eq "" exists "HOME-only fallback: writes new roost.conf"
assert_contains "$(cat "$newconf2" 2>/dev/null)" 'set -g @roost-glyph-idle "zzz"' "HOME-only fallback: translates key and value"
after2="$(cksum "$legacy2")"
assert_eq "$after2" "$before2" "HOME-only fallback: legacy amux.conf untouched"

rm -rf "$homedir2"

# --- Case 3: roost.conf already exists -> migration must not run at all. ---
# The tty guard now runs first, so to even reach the migration `if` we must
# clear it with ROOST_INIT_ANSWERS=- and piped stdin — same as Cases 1/2.
# But here the target ALREADY exists, so the migration condition
# (`[ ! -f "$target" ]`) is false and the script instead falls through into
# the normal interactive flow, which legitimately backs up and rewrites an
# existing roost.conf from the (empty/default) answers. That rewrite is
# real, correct `roost init` behaviour and is not what this case is testing;
# a plain "is the file byte-identical" assertion would be vacuously true for
# the wrong reason before the guard moved, and would flip to a false
# failure now that clearing the guard is required to reach the code at all.
# So this case asserts the two things that actually distinguish "migration
# ran instead" from "the normal ask-flow ran": (a) the normal flow always
# backs up an existing target before overwriting — migration's code path
# has no backup step at all, so a missing backup means migration clobbered
# it directly; (b) migration's output would be byte-identical to a raw,
# unbackuped sed translation of the legacy file — the interactive flow's
# output never is, because it always carries the full default key set.
# Verified against a mutant (`if [ -f "$legacy" ]`, dropping the
# target-absent check) that both assertions catch: no .bak was written and
# the resulting file WAS the raw translation.
cfgdir3="$(mktemp -d /tmp/amx.XXXX)"
mkdir -p "$cfgdir3/amux" "$cfgdir3/roost"
legacy3="$cfgdir3/amux/amux.conf"
printf 'set -g @amux-notify-backend "auto"\n' > "$legacy3"
printf '# already migrated / hand-written\nset -g @roost-notify-backend "tmux"\n' > "$cfgdir3/roost/roost.conf"
legacy3_before="$(cksum "$legacy3")"
naive_translation="$(sed 's/@amux-/@roost-/g' "$legacy3")"

printf '' | HOME=/nonexistent XDG_CONFIG_HOME="$cfgdir3" ROOST_INIT_ANSWERS=- "$ROOST_INIT" >/dev/null 2>&1

if ls "$cfgdir3/roost/"*.bak >/dev/null 2>&1; then
  assert_eq ok ok "an existing roost.conf is backed up before any rewrite (proves the normal flow ran, not migration)"
else
  assert_eq "" backup "an existing roost.conf is backed up before any rewrite (proves the normal flow ran, not migration)"
fi

actual="$(cat "$cfgdir3/roost/roost.conf" 2>/dev/null)"
if [ "$actual" = "$naive_translation" ]; then
  assert_eq "raw-migration-output" "interactive-output" "existing roost.conf's new content is not migration's raw translation of the legacy file"
else
  assert_eq ok ok "existing roost.conf's new content is not migration's raw translation of the legacy file"
fi

legacy3_after="$(cksum "$legacy3")"
assert_eq "$legacy3_after" "$legacy3_before" "legacy amux.conf untouched even when roost.conf already exists"

rm -rf "$cfgdir3"

# --- Case 4: the tty guard precedes migration -> a non-tty call with no ----
# --- scripted answers must exit non-zero and write NOTHING, even though ----
# --- migration's own preconditions (legacy present, new file absent) hold. -
cfgdir4="$(mktemp -d /tmp/amx.XXXX)"
mkdir -p "$cfgdir4/amux"
printf 'set -g @amux-notify-backend "auto"\n' > "$cfgdir4/amux/amux.conf"

HOME=/nonexistent XDG_CONFIG_HOME="$cfgdir4" "$ROOST_INIT" </dev/null >/dev/null 2>&1
rc4=$?

assert_eq "$rc4" "1" "non-tty call with no scripted answers exits non-zero (guard, not migration, runs first)"
if [ -e "$cfgdir4/roost" ]; then
  assert_eq "wrote" "no-write" "a failing non-tty call writes no roost.conf, even though legacy exists and the new file is absent"
else
  assert_eq ok ok "a failing non-tty call writes no roost.conf, even though legacy exists and the new file is absent"
fi

rm -rf "$cfgdir4"

# --- Case 5: an unreadable legacy file fails loudly and leaves nothing -----
# --- behind, instead of silently writing a truncated/empty roost.conf. -----
# Migration used to `sed ... > "$target"` directly: the redirect truncates
# the target before sed ever runs, and sed's exit status was never checked.
# An unreadable (or otherwise failing-to-read) legacy file produced a
# zero-byte roost.conf, printed a success message, and exited 0 — and
# because migration only fires while roost.conf is absent, the loss was
# permanent; a later run would see the (empty) target and never retry.
# Root can read a chmod 000 file, so this case is a no-op under root rather
# than a false failure.
if [ "$(id -u)" = "0" ]; then
  printf '  SKIP: unreadable legacy file case (running as root, chmod 000 has no effect)\n'
else
  cfgdir5="$(mktemp -d /tmp/amx.XXXX)"
  mkdir -p "$cfgdir5/amux"
  legacy5="$cfgdir5/amux/amux.conf"
  printf 'set -g @amux-notify-backend "auto"\n' > "$legacy5"
  chmod 000 "$legacy5"

  printf '' | HOME=/nonexistent XDG_CONFIG_HOME="$cfgdir5" ROOST_INIT_ANSWERS=- "$ROOST_INIT" >/dev/null 2>/dev/null
  rc5=$?

  assert_eq "$rc5" "1" "an unreadable legacy file makes migration exit non-zero, not silently succeed"
  if [ -e "$cfgdir5/roost/roost.conf" ]; then
    assert_eq "wrote" "no-write" "an unreadable legacy file leaves no roost.conf behind (no truncated/empty file)"
  else
    assert_eq ok ok "an unreadable legacy file leaves no roost.conf behind (no truncated/empty file)"
  fi

  # Leftover .roost.XXXXXX temp files would also indicate a non-atomic write.
  if ls "$cfgdir5/roost"/.roost.* >/dev/null 2>&1; then
    assert_eq "leftover-tmp" "no-tmp" "no leftover migration temp file after a failed migration"
  else
    assert_eq ok ok "no leftover migration temp file after a failed migration"
  fi

  chmod 600 "$legacy5"   # restore before cleanup, in case rm needs to read the dir on some platform
  rm -rf "$cfgdir5"
fi
