#!/usr/bin/env bash
# tests/test-roost-config-migration.sh — `roost init` carries a legacy
# ~/.config/amux/amux.conf across to ~/.config/roost/roost.conf, translating
# @amux-* keys to @roost-* and leaving @agent_* keys (and the old file
# itself) untouched. The running amux server may still be reading the old
# file, so this never writes, moves, or deletes it.
set -u
. "$(dirname "$0")/lib.sh"
HERE="$(cd "$(dirname "$0")/.." && pwd)"
ROOST_INIT="$HERE/scripts/roost-init"

# --- Case 1: XDG_CONFIG_HOME set, legacy present, new file absent. ---------
cfgdir="$(mktemp -d /tmp/amx.XXXX)"
homedir="$(mktemp -d /tmp/amx.XXXX)"   # decoy HOME: must never be touched
mkdir -p "$cfgdir/amux"
legacy="$cfgdir/amux/amux.conf"
cat > "$legacy" <<'EOF'
# Generated by amux init. Re-run amux init to change, or edit by hand.
set -g @amux-notify-backend "auto"
set -g @amux-color-active-bg "#ff0000"
set -g @agent_state "idle"
set -g @agent_glyph "🟢"
EOF

before_sum="$(cksum "$legacy")"
before_bytes="$(wc -c < "$legacy")"

out="$(HOME="$homedir" XDG_CONFIG_HOME="$cfgdir" "$ROOST_INIT" 2>&1)"
rc=$?

newconf="$cfgdir/roost/roost.conf"

assert_eq "$rc" "0" "migration exits 0"
[ -f "$newconf" ] && assert_eq ok ok "writes new roost.conf" || assert_eq "" exists "writes new roost.conf"

assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @roost-notify-backend "auto"' "translates @amux-notify-backend, value carried across"
assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @roost-color-active-bg "#ff0000"' "translates @amux-color-active-bg, value carried across"
assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @agent_state "idle"' "leaves unbranded @agent_state key unchanged"
assert_contains "$(cat "$newconf" 2>/dev/null)" 'set -g @agent_glyph "🟢"' "leaves unbranded @agent_glyph key unchanged"

case "$(cat "$newconf" 2>/dev/null)" in
  *@amux-*) assert_eq "has-amux-keys" "no-amux-keys" "new file has no leftover @amux- keys" ;;
  *)        assert_eq ok ok "new file has no leftover @amux- keys" ;;
esac

after_sum="$(cksum "$legacy")"
after_bytes="$(wc -c < "$legacy")"
assert_eq "$after_sum" "$before_sum" "legacy amux.conf is byte-identical after migration (cksum)"
assert_eq "$after_bytes" "$before_bytes" "legacy amux.conf size unchanged after migration"

if [ -e "$homedir/.config" ]; then
  assert_eq "touched" "untouched" "decoy HOME is never written to when XDG_CONFIG_HOME is set"
else
  assert_eq ok ok "decoy HOME is never written to when XDG_CONFIG_HOME is set"
fi

rm -rf "$cfgdir" "$homedir"

# --- Case 2: no XDG_CONFIG_HOME, falls back to $HOME/.config. --------------
homedir2="$(mktemp -d /tmp/amx.XXXX)"
mkdir -p "$homedir2/.config/amux"
legacy2="$homedir2/.config/amux/amux.conf"
printf 'set -g @amux-glyph-idle "zzz"\n' > "$legacy2"
before2="$(cksum "$legacy2")"

env -u XDG_CONFIG_HOME HOME="$homedir2" "$ROOST_INIT" >/dev/null 2>&1
newconf2="$homedir2/.config/roost/roost.conf"
[ -f "$newconf2" ] && assert_eq ok ok "HOME-only fallback: writes new roost.conf" || assert_eq "" exists "HOME-only fallback: writes new roost.conf"
assert_contains "$(cat "$newconf2" 2>/dev/null)" 'set -g @roost-glyph-idle "zzz"' "HOME-only fallback: translates key and value"
after2="$(cksum "$legacy2")"
assert_eq "$after2" "$before2" "HOME-only fallback: legacy amux.conf untouched"

rm -rf "$homedir2"

# --- Case 3: roost.conf already exists -> migration must not overwrite it. -
cfgdir3="$(mktemp -d /tmp/amx.XXXX)"
mkdir -p "$cfgdir3/amux" "$cfgdir3/roost"
printf 'set -g @amux-notify-backend "auto"\n' > "$cfgdir3/amux/amux.conf"
printf '# already migrated / hand-written\nset -g @roost-notify-backend "tmux"\n' > "$cfgdir3/roost/roost.conf"
legacy3_before="$(cksum "$cfgdir3/amux/amux.conf")"
existing_before="$(cksum "$cfgdir3/roost/roost.conf")"

HOME=/nonexistent XDG_CONFIG_HOME="$cfgdir3" "$ROOST_INIT" </dev/null >/dev/null 2>&1

existing_after="$(cksum "$cfgdir3/roost/roost.conf")"
legacy3_after="$(cksum "$cfgdir3/amux/amux.conf")"
assert_eq "$existing_after" "$existing_before" "an existing roost.conf is not overwritten by migration"
assert_eq "$legacy3_after" "$legacy3_before" "legacy amux.conf untouched even when roost.conf already exists"

rm -rf "$cfgdir3"
