# amux-config.sh — sourced helpers shared by amux-init and amux-settings.
# No side effects on source. Requires amux-themes.sh sourced alongside.

amux_cfg_path() { printf '%s/amux/amux.conf' "${XDG_CONFIG_HOME:-$HOME/.config}"; }

# amux_glyphset NAME -> "error blocked working done idle" (space-separated).
# Urgency order, matching the tab badge and the status rollup, so there is a
# single canonical order for the five states across the codebase.
# \xHH bytes, not \uXXXX: bash 3.2's printf has no \u. Unknown -> emoji.
amux_glyphset() {
  case "$1" in
    orbs)  printf '%s %s %s %s %s' "🟣" "🔴" "🟡" "🔵" "🟢" ;;
    ascii) printf '%s %s %s %s %s' "[x]" "[!]" "[~]" "[+]" "[·]" ;;
    nerd)  printf '%s %s %s %s %s' \
             "$(printf '\xef\x83\xa7')" \
             "$(printf '\xef\x81\xb1')" "$(printf '\xef\x89\x92')" \
             "$(printf '\xef\x80\x8c')" "$(printf '\xef\x86\x86')" ;;
    *)     printf '%s %s %s %s %s' "💥" "🛑" "⏳" "✅" "💤" ;;
  esac
}

# amux_sep NAME -> wedge bytes for "triangle", empty otherwise.
amux_sep() { case "$1" in triangle) printf '\xee\x82\xb0' ;; *) printf '' ;; esac; }

# amux_cfg_set KEY VALUE -> surgically set one `set -g KEY "VALUE"` line,
# preserving every other line. Atomic (temp in same dir + mv).
amux_cfg_set() {
  local key="$1" val="$2" target dir tmp line mode
  target="$(amux_cfg_path)"; dir="$(dirname "$target")"
  mkdir -p "$dir"
  tmp="$(mktemp "$dir/.amux.XXXXXX")" || return 1
  line="set -g $key \"$val\""

  # Build the temp file; clean up and return 1 on failure
  if [ -f "$target" ] && grep -q "^set -g $key " "$target" 2>/dev/null; then
    AMUX_K="$key" AMUX_L="$line" awk '
      $0 ~ ("^set -g " ENVIRON["AMUX_K"] " ") { print ENVIRON["AMUX_L"]; next }
      { print }' "$target" > "$tmp" || { rm -f "$tmp"; return 1; }
  elif [ -f "$target" ]; then
    cat "$target" > "$tmp" || { rm -f "$tmp"; return 1; }
    printf '%s\n' "$line" >> "$tmp" || { rm -f "$tmp"; return 1; }
  else
    printf '%s\n' "# Generated by amux. Re-run amux init/settings or edit by hand." > "$tmp" || { rm -f "$tmp"; return 1; }
    printf '%s\n' "$line" >> "$tmp" || { rm -f "$tmp"; return 1; }
  fi

  # Preserve existing file's permissions if it exists
  if [ -f "$target" ]; then
    # GNU-first: `stat -c` works on Linux and fails cleanly on macOS (falls to
    # BSD `-f`). The reverse order is NOT portable — GNU `stat -f` means
    # "filesystem status", so it does not fail, and the fallback never fires.
    mode="$(stat -c '%a' "$target" 2>/dev/null || stat -f '%Lp' "$target" 2>/dev/null)"
    [ -n "$mode" ] && chmod "$mode" "$tmp"
  fi

  # Promote temp file and return its exit status
  mv "$tmp" "$target"
}

# amux_cfg_tmux ARGS -> talk to the test socket if set, else the amux server.
#
# Deliberately NO "server we are running inside" step, unlike amux-status,
# amux-switch, amux-notify, amux-next-blocked and amux-migrate-state. Those are
# only ever invoked from within an amux server (a binding, a popup, the conf),
# so inheriting $TMUX is always right for them. This lib backs `amux init` and
# `amux settings`, which a user may legitimately run from a normal terminal —
# including one inside their REGULAR tmux. Inheriting $TMUX there would write
# amux's theme and glyph options into their everyday tmux server. Addressing
# -L amux by name is the correct behaviour for this one.
amux_cfg_tmux() {
  if [ -n "${AMUX_CONFIG_SOCK:-}" ]; then tmux -S "$AMUX_CONFIG_SOCK" "$@"
  else tmux -L amux "$@"; fi
}

# amux_opt KEY -> current value: from the running server, else the config file.
amux_opt() {
  local key="$1" target line v
  if amux_cfg_tmux has-session 2>/dev/null; then
    amux_cfg_tmux show-options -gqv "$key" 2>/dev/null; return
  fi
  target="$(amux_cfg_path)"; [ -f "$target" ] || return 0
  line="$(grep "^set -g $key " "$target" 2>/dev/null | tail -1)"
  case "$line" in
    *\"*) v="${line#*\"}"; v="${v%\"}"; printf '%s' "$v" ;;
    *) : ;;
  esac
}

# amux_current_theme -> name matching the current 6 colours, else "custom".
amux_current_theme() {
  local cur t
  cur="$(amux_opt @amux-color-bar-bg) $(amux_opt @amux-color-bar-fg) $(amux_opt @amux-color-logo-bg) $(amux_opt @amux-color-active-bg) $(amux_opt @amux-color-active-fg) $(amux_opt @amux-color-idle-fg)"
  for t in $(amux_theme_names); do
    [ "$(amux_theme "$t")" = "$cur" ] && { printf '%s' "$t"; return; }
  done
  printf 'custom'
}

# amux_current_glyphset -> name matching the current glyphs, else "custom".
#
# Matches on the FOUR original glyphs, not all five. Every config written
# before the error state existed has no @amux-glyph-error, and tmux/amux.conf
# supplies the emoji 💥 as the global default whatever set the user picked — so
# requiring a fifth match would report "custom" for every existing user until
# they re-picked. The cost is that a hand-customised error glyph alone does not
# make a set read as "custom"; that is the better trade.
amux_current_glyphset() {
  local cur g
  cur="$(amux_opt @amux-glyph-blocked) $(amux_opt @amux-glyph-working) $(amux_opt @amux-glyph-done) $(amux_opt @amux-glyph-idle)"
  for g in emoji orbs ascii nerd; do
    set -f; set -- $(amux_glyphset "$g"); set +f
    [ "$2 $3 $4 $5" = "$cur" ] && { printf '%s' "$g"; return; }
  done
  printf 'custom'
}

# amux_apply_live HOME -> reload the running server. No server -> no-op.
amux_apply_live() {
  local home="$1"
  amux_cfg_tmux has-session 2>/dev/null || return 0
  amux_cfg_tmux source-file -F "#{@amux-home}/tmux/amux.conf" 2>/dev/null || \
    amux_cfg_tmux source-file "$home/tmux/amux.conf" 2>/dev/null || true
  amux_cfg_tmux source-file -qF "#{@amux-user-conf}" 2>/dev/null || true
  amux_cfg_tmux refresh-client -S 2>/dev/null || true
}

# amux_menu_row SAVED VALUE SUFFIX -> "VALUE<TAB><mark>VALUE<SUFFIX>".
# <mark> is a fixed 2-col "✓ " (saved) or "  " (not), so the highlight moving
# during preview never repositions the text. Field 1 (VALUE) is a hidden key.
amux_menu_row() {
  local saved="$1" value="$2" suffix="${3:-}" mark
  if [ "$saved" = "$value" ]; then mark="✓ "; else mark="  "; fi
  printf '%s\t%s%s%s\n' "$value" "$mark" "$value" "$suffix"
}

# amux_preview_keys TYPE -> the @-options a preview of TYPE touches.
amux_preview_keys() {
  case "$1" in
    theme)     echo "@amux-color-bar-bg @amux-color-bar-fg @amux-color-logo-bg @amux-color-active-bg @amux-color-active-fg @amux-color-idle-fg" ;;
    glyphs)    echo "@amux-glyph-error @amux-glyph-blocked @amux-glyph-working @amux-glyph-done @amux-glyph-idle" ;;
    separator) echo "@amux-sep-left @amux-sep-right" ;;
  esac
}

# amux_preview_apply TYPE VALUE -> apply to the RUNNING server only (no config write).
amux_preview_apply() {
  local type="$1" value="$2" s
  case "$type" in
    theme)
      set -f; set -- $(amux_theme "$value"); set +f
      [ "$#" -eq 6 ] || return 0
      amux_cfg_tmux set-option -g @amux-color-bar-bg    "$1" 2>/dev/null || true
      amux_cfg_tmux set-option -g @amux-color-bar-fg    "$2" 2>/dev/null || true
      amux_cfg_tmux set-option -g @amux-color-logo-bg   "$3" 2>/dev/null || true
      amux_cfg_tmux set-option -g @amux-color-active-bg "$4" 2>/dev/null || true
      amux_cfg_tmux set-option -g @amux-color-active-fg "$5" 2>/dev/null || true
      amux_cfg_tmux set-option -g @amux-color-idle-fg   "$6" 2>/dev/null || true
      ;;
    glyphs)
      set -f; set -- $(amux_glyphset "$value"); set +f
      [ "$#" -eq 5 ] || return 0
      amux_cfg_tmux set-option -g @amux-glyph-error   "$1" 2>/dev/null || true
      amux_cfg_tmux set-option -g @amux-glyph-blocked "$2" 2>/dev/null || true
      amux_cfg_tmux set-option -g @amux-glyph-working "$3" 2>/dev/null || true
      amux_cfg_tmux set-option -g @amux-glyph-done    "$4" 2>/dev/null || true
      amux_cfg_tmux set-option -g @amux-glyph-idle    "$5" 2>/dev/null || true
      ;;
    separator)
      s="$(amux_sep "$value")"
      amux_cfg_tmux set-option -g @amux-sep-left  "$s" 2>/dev/null || true
      amux_cfg_tmux set-option -g @amux-sep-right "$s" 2>/dev/null || true
      ;;
  esac
  amux_cfg_tmux refresh-client -S 2>/dev/null || true
}

# amux_snapshot TYPE FILE -> capture current server values of TYPE's options.
amux_snapshot() {
  local type="$1" file="$2" k v
  : > "$file"
  for k in $(amux_preview_keys "$type"); do
    v="$(amux_cfg_tmux show-options -gqv "$k" 2>/dev/null)"
    printf '%s\t%s\n' "$k" "$v" >> "$file"
  done
}

# amux_restore TYPE FILE -> re-apply a snapshot to the server.
amux_restore() {
  local file="$2" k v tab
  [ -f "$file" ] || return 0
  tab="$(printf '\t')"
  while IFS="$tab" read -r k v; do
    [ -n "$k" ] && amux_cfg_tmux set-option -g "$k" "$v" 2>/dev/null || true
  done < "$file"
  amux_cfg_tmux refresh-client -S 2>/dev/null || true
}
