# roost-config.sh — sourced helpers shared by roost-init and roost-settings.
# No side effects on source. Requires roost-themes.sh sourced alongside.

roost_cfg_path() { printf '%s/roost/roost.conf' "${XDG_CONFIG_HOME:-$HOME/.config}"; }

# roost_glyphset NAME -> "error blocked working done idle" (space-separated).
# Urgency order, matching the tab badge and the status rollup, so there is a
# single canonical order for the five states across the codebase.
# \xHH bytes, not \uXXXX: bash 3.2's printf has no \u. Unknown -> emoji.
roost_glyphset() {
  case "$1" in
    orbs)  printf '%s %s %s %s %s' "🟣" "🔴" "🟡" "🔵" "🟢" ;;
    ascii) printf '%s %s %s %s %s' "[x]" "[!]" "[~]" "[+]" "[·]" ;;
    nerd)  printf '%s %s %s %s %s' \
             "$(printf '\xef\x83\xa7')" \
             "$(printf '\xef\x81\xb1')" "$(printf '\xef\x89\x92')" \
             "$(printf '\xef\x80\x8c')" "$(printf '\xef\x86\x86')" ;;
    *)     printf '%s %s %s %s %s' "💥" "🛑" "⏳" "✅" "💤" ;;
  esac
}

# roost_sep NAME -> wedge bytes for "triangle", empty otherwise.
roost_sep() { case "$1" in triangle) printf '\xee\x82\xb0' ;; *) printf '' ;; esac; }

# roost_cfg_set KEY VALUE -> surgically set one `set -g KEY "VALUE"` line,
# preserving every other line. Atomic (temp in same dir + mv).
roost_cfg_set() {
  local key="$1" val="$2" target dir tmp line mode
  target="$(roost_cfg_path)"; dir="$(dirname "$target")"
  mkdir -p "$dir"
  tmp="$(mktemp "$dir/.roost.XXXXXX")" || return 1
  line="set -g $key \"$val\""

  # Build the temp file; clean up and return 1 on failure
  if [ -f "$target" ] && grep -q "^set -g $key " "$target" 2>/dev/null; then
    ROOST_K="$key" ROOST_L="$line" awk '
      $0 ~ ("^set -g " ENVIRON["ROOST_K"] " ") { print ENVIRON["ROOST_L"]; next }
      { print }' "$target" > "$tmp" || { rm -f "$tmp"; return 1; }
  elif [ -f "$target" ]; then
    cat "$target" > "$tmp" || { rm -f "$tmp"; return 1; }
    printf '%s\n' "$line" >> "$tmp" || { rm -f "$tmp"; return 1; }
  else
    printf '%s\n' "# Generated by roost. Re-run roost init/settings or edit by hand." > "$tmp" || { rm -f "$tmp"; return 1; }
    printf '%s\n' "$line" >> "$tmp" || { rm -f "$tmp"; return 1; }
  fi

  # Preserve existing file's permissions if it exists
  if [ -f "$target" ]; then
    # GNU-first: `stat -c` works on Linux and fails cleanly on macOS (falls to
    # BSD `-f`). The reverse order is NOT portable — GNU `stat -f` means
    # "filesystem status", so it does not fail, and the fallback never fires.
    mode="$(stat -c '%a' "$target" 2>/dev/null || stat -f '%Lp' "$target" 2>/dev/null)"
    [ -n "$mode" ] && chmod "$mode" "$tmp"
  fi

  # Promote temp file and return its exit status
  mv "$tmp" "$target"
}

# roost_cfg_tmux ARGS -> talk to the test socket if set, else the roost server.
#
# Deliberately NO "server we are running inside" step, unlike roost-status,
# roost-switch, roost-notify and roost-next-blocked. Those are
# only ever invoked from within a roost server (a binding, a popup, the conf),
# so inheriting $TMUX is always right for them. This lib backs `roost init` and
# `roost settings`, which a user may legitimately run from a normal terminal —
# including one inside their REGULAR tmux. Inheriting $TMUX there would write
# roost's theme and glyph options into their everyday tmux server. Addressing
# -L roost by name is the correct behaviour for this one.
roost_cfg_tmux() {
  if [ -n "${ROOST_CONFIG_SOCK:-}" ]; then tmux -S "$ROOST_CONFIG_SOCK" "$@"
  else tmux -L roost "$@"; fi
}

# roost_cfg_file_opt FILE KEY -> the value of the last `set -g KEY "VALUE"` line
# in FILE; empty when FILE or the line is absent.
#
# File-scoped on purpose, and not just an inlined half of roost_opt: the
# migration in roost-init has to read a config that is not the user's live one
# yet (it is still a temp file), and doctor has to say what the SAVED file
# holds rather than what a running server happens to be showing. roost_opt
# answers from the server first, so neither caller can use it.
roost_cfg_file_opt() {
  local file="$1" key="$2" line v
  [ -f "$file" ] || return 0
  line="$(grep "^set -g $key " "$file" 2>/dev/null | tail -1)"
  case "$line" in
    *\"*) v="${line#*\"}"; v="${v%\"}"; printf '%s' "$v" ;;
    *) : ;;
  esac
}

# roost_cfg_file_has FILE KEY -> success when FILE carries a `set -g KEY ` line
# at all.
#
# Distinct from roost_cfg_file_opt returning empty, and the distinction is the
# whole point: a key that was never written and a key deliberately set to ""
# both read as an empty value, and only the presence of the LINE tells you
# which one happened. Everything below that decides "this config predates the
# error state" depends on that difference.
roost_cfg_file_has() {
  [ -f "$1" ] && grep -q "^set -g $2 " "$1" 2>/dev/null
}

# roost_opt KEY -> current value: from the running server, else the config file.
roost_opt() {
  local key="$1"
  if roost_cfg_tmux has-session 2>/dev/null; then
    roost_cfg_tmux show-options -gqv "$key" 2>/dev/null; return
  fi
  roost_cfg_file_opt "$(roost_cfg_path)" "$key"
}

# roost_current_theme -> name matching the current 6 colours, else "custom".
roost_current_theme() {
  local cur t
  cur="$(roost_opt @roost-color-bar-bg) $(roost_opt @roost-color-bar-fg) $(roost_opt @roost-color-logo-bg) $(roost_opt @roost-color-active-bg) $(roost_opt @roost-color-active-fg) $(roost_opt @roost-color-idle-fg)"
  for t in $(roost_theme_names); do
    [ "$(roost_theme "$t")" = "$cur" ] && { printf '%s' "$t"; return; }
  done
  printf 'custom'
}

# roost_glyphset_match BLOCKED WORKING DONE IDLE -> the name of the set those
# four glyphs come from, else "custom".
#
# Matches on the FOUR original glyphs, not all five. Every config written
# before the error state existed has no @roost-glyph-error, and tmux/roost.conf
# supplies the emoji 💥 as the global default whatever set the user picked — so
# requiring a fifth match would report "custom" for every existing user until
# they re-picked. The cost is that a hand-customised error glyph alone does not
# make a set read as "custom"; that is the better trade.
#
# Takes the four values as arguments rather than reading them itself, because
# there are two sources that matter: the live server / user config (see
# roost_current_glyphset) and an arbitrary file (see
# roost_backfill_glyph_error). One matcher, so the two can never drift.
roost_glyphset_match() {
  local cur="$1 $2 $3 $4" g
  for g in emoji orbs ascii nerd; do
    set -f; set -- $(roost_glyphset "$g"); set +f
    [ "$2 $3 $4 $5" = "$cur" ] && { printf '%s' "$g"; return; }
  done
  printf 'custom'
}

# roost_current_glyphset -> name matching the current glyphs, else "custom".
roost_current_glyphset() {
  roost_glyphset_match \
    "$(roost_opt @roost-glyph-blocked)" "$(roost_opt @roost-glyph-working)" \
    "$(roost_opt @roost-glyph-done)"    "$(roost_opt @roost-glyph-idle)"
}

# roost_backfill_glyph_error FILE -> append the error glyph that FILE's own
# glyph set implies, when FILE predates the error state. No-op otherwise.
#
# The error state shipped after the four original glyphs, so a config written
# before it has four glyph lines and no @roost-glyph-error, and the bar falls
# back to tmux/roost.conf's global 💥 — an emoji in a bar the user chose not to
# have emoji in, or a 2-cell glyph among 1-cell ones.
#
# The safety argument is the whole design, so read it before changing this:
#
#   - It only ever APPENDS the fifth glyph. The four existing lines are never
#     rewritten, so nothing the user already chose can be lost.
#   - It only fires when those four are an exact match for a named set, so the
#     value appended is derived from what the file already says — never
#     invented. A hand-customised set matches nothing, reads as "custom", and
#     is left exactly as it was.
#   - It only fires when there is no @roost-glyph-error line at all. A user who
#     deliberately set a custom error glyph keeps it: roost_cfg_file_has, not
#     an empty value, is what decides that (a key set to "" is a choice too).
#
# Returns 0 when there was nothing to do; non-zero only when the append itself
# failed, so a caller building a temp file can abort rather than promote a
# half-written config.
roost_backfill_glyph_error() {
  local file="$1" name
  roost_cfg_file_has "$file" @roost-glyph-error && return 0
  name="$(roost_glyphset_match \
    "$(roost_cfg_file_opt "$file" @roost-glyph-blocked)" \
    "$(roost_cfg_file_opt "$file" @roost-glyph-working)" \
    "$(roost_cfg_file_opt "$file" @roost-glyph-done)" \
    "$(roost_cfg_file_opt "$file" @roost-glyph-idle)")"
  [ "$name" = custom ] && return 0
  # Same column alignment roost-init's own heredoc uses, so a migrated file and
  # a freshly written one are indistinguishable to a human reading them.
  set -f; set -- $(roost_glyphset "$name"); set +f
  printf 'set -g @roost-glyph-error   "%s"\n' "$1" >> "$file"
}

# roost_apply_live HOME -> reload the running server. No server -> no-op.
roost_apply_live() {
  local home="$1"
  roost_cfg_tmux has-session 2>/dev/null || return 0
  roost_cfg_tmux source-file -F "#{@roost-home}/tmux/roost.conf" 2>/dev/null || \
    roost_cfg_tmux source-file "$home/tmux/roost.conf" 2>/dev/null || true
  roost_cfg_tmux source-file -qF "#{@roost-user-conf}" 2>/dev/null || true
  roost_cfg_tmux refresh-client -S 2>/dev/null || true
}

# roost_menu_row SAVED VALUE SUFFIX -> "VALUE<TAB><mark>VALUE<SUFFIX>".
# <mark> is a fixed 2-col "✓ " (saved) or "  " (not), so the highlight moving
# during preview never repositions the text. Field 1 (VALUE) is a hidden key.
roost_menu_row() {
  local saved="$1" value="$2" suffix="${3:-}" mark
  if [ "$saved" = "$value" ]; then mark="✓ "; else mark="  "; fi
  printf '%s\t%s%s%s\n' "$value" "$mark" "$value" "$suffix"
}

# roost_preview_keys TYPE -> the @-options a preview of TYPE touches.
roost_preview_keys() {
  case "$1" in
    theme)     echo "@roost-color-bar-bg @roost-color-bar-fg @roost-color-logo-bg @roost-color-active-bg @roost-color-active-fg @roost-color-idle-fg" ;;
    glyphs)    echo "@roost-glyph-error @roost-glyph-blocked @roost-glyph-working @roost-glyph-done @roost-glyph-idle" ;;
    separator) echo "@roost-sep-left @roost-sep-right" ;;
  esac
}

# roost_preview_apply TYPE VALUE -> apply to the RUNNING server only (no config write).
roost_preview_apply() {
  local type="$1" value="$2" s
  case "$type" in
    theme)
      set -f; set -- $(roost_theme "$value"); set +f
      [ "$#" -eq 6 ] || return 0
      roost_cfg_tmux set-option -g @roost-color-bar-bg    "$1" 2>/dev/null || true
      roost_cfg_tmux set-option -g @roost-color-bar-fg    "$2" 2>/dev/null || true
      roost_cfg_tmux set-option -g @roost-color-logo-bg   "$3" 2>/dev/null || true
      roost_cfg_tmux set-option -g @roost-color-active-bg "$4" 2>/dev/null || true
      roost_cfg_tmux set-option -g @roost-color-active-fg "$5" 2>/dev/null || true
      roost_cfg_tmux set-option -g @roost-color-idle-fg   "$6" 2>/dev/null || true
      ;;
    glyphs)
      set -f; set -- $(roost_glyphset "$value"); set +f
      [ "$#" -eq 5 ] || return 0
      roost_cfg_tmux set-option -g @roost-glyph-error   "$1" 2>/dev/null || true
      roost_cfg_tmux set-option -g @roost-glyph-blocked "$2" 2>/dev/null || true
      roost_cfg_tmux set-option -g @roost-glyph-working "$3" 2>/dev/null || true
      roost_cfg_tmux set-option -g @roost-glyph-done    "$4" 2>/dev/null || true
      roost_cfg_tmux set-option -g @roost-glyph-idle    "$5" 2>/dev/null || true
      ;;
    separator)
      s="$(roost_sep "$value")"
      roost_cfg_tmux set-option -g @roost-sep-left  "$s" 2>/dev/null || true
      roost_cfg_tmux set-option -g @roost-sep-right "$s" 2>/dev/null || true
      ;;
  esac
  roost_cfg_tmux refresh-client -S 2>/dev/null || true
}

# roost_snapshot TYPE FILE -> capture current server values of TYPE's options.
roost_snapshot() {
  local type="$1" file="$2" k v
  : > "$file"
  for k in $(roost_preview_keys "$type"); do
    v="$(roost_cfg_tmux show-options -gqv "$k" 2>/dev/null)"
    printf '%s\t%s\n' "$k" "$v" >> "$file"
  done
}

# roost_restore TYPE FILE -> re-apply a snapshot to the server.
roost_restore() {
  local file="$2" k v tab
  [ -f "$file" ] || return 0
  tab="$(printf '\t')"
  while IFS="$tab" read -r k v; do
    [ -n "$k" ] && roost_cfg_tmux set-option -g "$k" "$v" 2>/dev/null || true
  done < "$file"
  roost_cfg_tmux refresh-client -S 2>/dev/null || true
}
